feat: 自动播放
go-musicfox/go-musicfox pull request #133
Opened 2023-06-28 15:16 UTC by imxyy1soope1

添加了自动播放功能，支持自定义歌单、offset、随机模式

2023-06-29 15:25 UTC, anhoder commented on pkg/ui/netease.go
这里可以在程序初始化完成后调用已有方法进到对应的菜单下再进行播放，随机播放也可以直接用现有的随机播放模式，这样逻辑更简洁，后续维护起来也简单

2023-06-29 15:25 UTC, anhoder commented on pkg/ui/player.go
> +		if isManual && p.curSongIndex < len(p.playlist)-1 {
按上面的方案这里也不需要特殊处理了

2023-06-29 15:25 UTC, anhoder commented on utils/utils.go
> -			if err != nil && runtime.GOOS == "windows" {
@kylezb 看下这个改动在Windows下有没有什么问题

2023-06-30 00:19 UTC, kylezb commented on utils/utils.go
> -			if err != nil && runtime.GOOS == "windows" {
> @kylezb 看下这个改动在Windows下有没有什么问题

有问题，Windows没法移动到到指定的目录，Windows的报错没有`invalid cross-device link`，Unix类系统好像没有这个跨磁盘的问题。

2023-06-30 07:43 UTC, imxyy1soope1 commented on pkg/ui/netease.go
OK，现在来改改

2023-06-30 07:43 UTC, imxyy1soope1 commented on utils/utils.go
> -			if err != nil && runtime.GOOS == "windows" {
好，我改改

2023-06-30 07:49 UTC, imxyy1soope1 commented on utils/utils.go
> -			if err != nil && runtime.GOOS == "windows" {
```go
if err != nil && (runtime.GOOS == "Windows" || strings.HasSuffix(err.Error(), "invalid cross-device link"))
```
这样应该可以吧

2023-06-30 09:26 UTC, kylezb commented on utils/utils.go
> -			if err != nil && runtime.GOOS == "windows" {
> ```go
> if err != nil && (runtime.GOOS == "Windows" || strings.HasSuffix(err.Error(), "invalid cross-device link"))
> ```
> 
> 这样应该可以吧

可以，但是你这写错了😒，我用你这代码跑了半天都下载不了，跑的我怀疑人生，满地找bug。
"Windows"  -> "windows"

2023-06-30 10:06 UTC, imxyy1soope1 commented on utils/utils.go
> -			if err != nil && runtime.GOOS == "windows" {
o，我的问题，太抱歉了qwq

2023-06-30 10:46 UTC, imxyy1soope1 commented on pkg/ui/netease.go
主要是有点强迫症，不想要进到菜单里面，要不我把获取歌单的逻辑包在函数里吧

2023-06-30 11:39 UTC, anhoder commented on pkg/ui/netease.go
但是为此要加一段很长而且没有复用性的特殊逻辑代码，后续维护还要额外考虑这个特殊分支，我这个代码强迫症有点难受😣

2023-06-30 11:44 UTC, imxyy1soope1 commented on pkg/ui/netease.go
这段代码可以考虑与菜单的逻辑复用

2023-06-30 13:19 UTC, imxyy1soope1 commented on pkg/ui/player.go
> +		if isManual && p.curSongIndex < len(p.playlist)-1 {
不是很看得懂，方便具体讲一下吗？

2023-06-30 15:06 UTC, anhoder commented on pkg/ui/player.go
> +		if isManual && p.curSongIndex < len(p.playlist)-1 {
这里是手动切歌跳过单曲循环限制？另外一个功能？

2023-06-30 15:06 UTC, anhoder requested changes
分开提PR吧

2023-06-30 23:29 UTC, imxyy1soope1 commented on pkg/ui/player.go
> +		if isManual && p.curSongIndex < len(p.playlist)-1 {
是的呢
实在是抱歉，在commit的时候忘记开新分支了，所以全部提交到这个pr里来了，有什么方法可以补救的吗？

2023-07-01 00:28 UTC, anhoder commented on pkg/ui/player.go
> +		if isManual && p.curSongIndex < len(p.playlist)-1 {
开个新分支，cherry pick出来

2023-07-02 09:01 UTC, closed without merging