feat: 自动缓存音乐
go-musicfox/go-musicfox pull request #139
Opened 2023-07-05 12:06 UTC by imxyy1soope1

添加了自动缓存音乐的功能，在获取歌曲url时会自动搜索缓存，如无缓存会自动下载。
注：如使用mpd,需要在mpd配置中配置`music_directory`为缓存目录，否则无法播放缓存音乐。
> TODO: 
> - 添加Mac支持（目前没有Mac开发环境）

2023-07-06 04:57 UTC, anhoder commented on hack/version.sh
> +echo Host          "$(cat /etc/hostname)"
Mac用不了，为啥改这个？

2023-07-06 05:35 UTC, anhoder requested changes

2023-07-06 05:35 UTC, anhoder commented on pkg/ui/menu_clear_cache.go
> +			err = filepath.WalkDir(cacheDir, func(path string, d fs.DirEntry, err error) error {
remove dir可以在utils里封个方法

2023-07-06 05:35 UTC, anhoder commented on pkg/ui/menu_clear_cache.go
> +type ClearCacheMenu struct {
清理缓存用快捷键就好了

2023-07-06 05:35 UTC, anhoder commented on utils/utils.go
> +	for _, file := range files {
func IsCached(song structs.Song) bool
改下这个方法，可以复用到这里

2023-07-06 05:35 UTC, anhoder commented on utils/utils.go
> +	if IsCached(song) {
这个if else里面很多一样的代码可以抽出来

2023-07-06 05:35 UTC, anhoder commented on utils/utils.go
> +	if configs.ConfigRegistry.MainCacheLimit > -1 && runtime.GOOS != "darwin" {
Mac放开，都要测的

2023-07-06 05:35 UTC, anhoder commented on pkg/configs/registry.go
> +	MainCacheLimit             int64                    // 缓存大小（以MB为单位），-1为不使用缓存，0为不限制，默认为-1
语义有问题吧，0为不使用，-1为不限制，默认0

2023-07-06 05:35 UTC, anhoder commented on pkg/player/mpd_player.go
> +			if !isCache {
是缓存  也可以设置这些信息吧？

2023-07-06 12:34 UTC, imxyy1soope1 commented on hack/version.sh
> +echo Host          "$(cat /etc/hostname)"
不好意思，不小心提交上来了，改这个是因为archlinux没有hostname命令

2023-07-06 12:34 UTC, imxyy1soope1 commented on utils/utils.go
> +	if configs.ConfigRegistry.MainCacheLimit > -1 && runtime.GOOS != "darwin" {
好

2023-07-06 12:35 UTC, imxyy1soope1 commented on pkg/configs/registry.go
> +	MainCacheLimit             int64                    // 缓存大小（以MB为单位），-1为不使用缓存，0为不限制，默认为-1
好

2023-07-06 12:35 UTC, imxyy1soope1 commented on pkg/player/mpd_player.go
> +			if !isCache {
mpd文档里说addtagid不能对本地歌曲使用，会报错

2023-07-06 12:53 UTC, imxyy1soope1 commented on pkg/ui/menu_clear_cache.go
> +			err = filepath.WalkDir(cacheDir, func(path string, d fs.DirEntry, err error) error {
```go
// utils.go
func ClearCache() error {
	cacheDir := GetCacheDir()
	return RemoveDir(cacheDir)
}

func RemoveDir(dir string) error {
	if FileOrDirExists(dir) {
		return filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
			return os.Remove(path)
		})
	} else {
		return os.MkdirAll(dir, os.ModePerm)
	}
}
```
这样可以吗？

2023-07-06 13:11 UTC, imxyy1soope1 commented on pkg/ui/menu_clear_cache.go
> +			err = filepath.WalkDir(cacheDir, func(path string, d fs.DirEntry, err error) error {
```go
// utils.go
func ClearCache() error {
	cacheDir := GetCacheDir()
	return ClearDir(cacheDir)
}

func ClearDir(dir string) error {
	if FileOrDirExists(dir) {
		err := os.RemoveAll(dir)
		if err != nil {
			return err
		}
	}
	return os.MkdirAll(dir, os.ModePerm)
}
```
好像这样的语义更明确

2023-07-06 13:19 UTC, anhoder commented on pkg/ui/menu_clear_cache.go
> +			err = filepath.WalkDir(cacheDir, func(path string, d fs.DirEntry, err error) error {
不存在不需要创建吧

2023-07-06 13:23 UTC, anhoder commented on pkg/player/mpd_player.go
> +			if !isCache {
好吧

2023-07-06 13:26 UTC, anhoder commented on hack/version.sh
> +echo Host          "$(cat /etc/hostname)"
可以换个兼容两种的写法

2023-07-06 14:35 UTC, imxyy1soope1 commented on pkg/ui/menu_clear_cache.go
> +			err = filepath.WalkDir(cacheDir, func(path string, d fs.DirEntry, err error) error {
ok

2023-07-06 14:40 UTC, imxyy1soope1 commented on pkg/player/mpd_player.go
> +			if !isCache {
所以在缓存了音乐之后还要调用SetSongTag来设置缓存音乐的tag，不然还是没法显示tag

2023-07-06 15:00 UTC, imxyy1soope1 commented on pkg/ui/menu_clear_cache.go
> +type ClearCacheMenu struct {
好了，现在用的u键（大小写）

2023-07-06 15:00 UTC, imxyy1soope1 commented on utils/utils.go
> +	for _, file := range files {
好了，现在改成了getCacheUri

2023-07-06 15:01 UTC, imxyy1soope1 commented on utils/utils.go
> +	if IsCached(song) {
好了

2023-07-06 15:01 UTC, imxyy1soope1 commented on hack/version.sh
> +echo Host          "$(cat /etc/hostname)"
现在的应该可以了
```bash
---SNIP---
if [[ ! `hostname -f` ]]; then
    echo Host          "$(cat /etc/hostname)"
else
    echo Host          "$(hostname -f)"
fi
---SNIP---
```

2023-07-08 05:26 UTC, anhoder reviewed
还有冲突需要解决

2023-07-08 05:26 UTC, anhoder commented on pkg/configs/registry.go
> +		MainCacheLimit:       -1,
-1 => 0

2023-07-08 09:11 UTC, imxyy1soope1 commented on pkg/configs/registry.go
> +		MainCacheLimit:       -1,
ok，忘记了

2023-07-13 05:04 UTC, anhoder commented
utils还有个冲突
<img width="965" alt="image" src="https://github.com/go-musicfox/go-musicfox/assets/27605589/b2f11567-7a97-453a-88f8-ed5cd257bc6b">

2023-07-14 04:52 UTC, imxyy1soope1 commented
> utils还有个冲突 <img alt="image" width="965" src="https://user-images.githubusercontent.com/27605589/253164493-b2f11567-7a97-453a-88f8-ed5cd257bc6b.png">

改好了
实在抱歉，不知道可以自己修改冲突

2023-07-14 08:35 UTC, merged